//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        public int ApplicationID { get; set; }
        public string FullName { get; set; }
        public decimal RequestAmount { get; set; }
        public string SectorID { get; set; }
        public string ContactNumber { get; set; }
        public string Location { get; set; }
        public string NearestLandmark { get; set; }
        public string DistributionMode { get; set; }
        public string MNO { get; set; }
        public string MomoNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string Comments { get; set; }
    }
}
