//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.API.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LMSdbContext : DbContext
    {
        public LMSdbContext()
            : base("name=LMSdbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoanApplication> LoanApplications { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<vwCustomersLoanOutstanding> vwCustomersLoanOutstandings { get; set; }
        public virtual DbSet<Transactions_Logs> Transactions_Logs { get; set; }
        public virtual DbSet<Loan_Outstanding_3> Loan_Outstanding_3 { get; set; }
    
        public virtual int usp_validateCustomerRefernceID(string refNo)
        {
            var refNoParameter = refNo != null ?
                new ObjectParameter("RefNo", refNo) :
                new ObjectParameter("RefNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_validateCustomerRefernceID", refNoParameter);
        }
    }
}
