//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions_Logs
    {
        public int LogID { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.DateTime> LogEntryDateTime { get; set; }
    }
}
