//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCustomersLoanOutstanding
    {
        public int EntryID { get; set; }
        public string Account_Number { get; set; }
        public string Account_Name { get; set; }
        public decimal Balance { get; set; }
    }
}
